mysql_databases:
  - name: "{{ vault_moodle_db_name }}"
    encoding: "utf8mb4"
    collation: "utf8mb4_unicode_ci"
mysql_users:
  - name: "{{ vault_moodle_db_user }}"
    host: "%"
    password: "{{ vault_moodle_db_password }}"
    priv: "{{ vault_moodle_db_name }}.*:ALL"
mysql_bind_address: "0.0.0.0"
mysql_enabled_on_startup: true
mysql_secure_installation: true
mysql_remove_anonymous_users: true
mysql_remove_remote_root: true
mysql_disallow_remote_root: true
mysql_root_password_update: true
mysql_remove_test_db: true
mysql_root_password: "{{ vault_mysql_root_password }}"
