---
moodle_version: "MOODLE_401_STABLE"
moodle_data_dir: "/var/www/moodledata"
# These variables will be replaced in the vault file
moodle_db_host: "localhost"
moodle_db_name: "moodle"
moodle_db_user: "moodle"
moodle_db_password: "password"
moodle_url: "http://localhost"
ports:
  - 80
  - 443
