- name: Create moodledata directory
  file:
    path: "{{ moodle_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set permissions on /var/www/html/moodle
  file:
    path: /var/www/html/moodle
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
