---
- name: Check if Moodle directory exists
  stat:
    path: /var/www/html/moodle
  register: moodle_dir

- name: Delete existing Moodle directory if it exists
  file:
    path: /var/www/html/moodle
    state: absent
  when: moodle_dir.stat.exists

- name: Download Moodle from Git repository
  git:
    repo: https://github.com/moodle/moodle.git
    dest: "/var/www/html/moodle"
    version: "{{ moodle_version }}"
    force: yes
  notify:
    - restart_apache2
