---
- name: Setup Moodle Database Server
  hosts: db
  become: yes

  vars_files:
    - ../vault/vault.yml

  roles:
    - geerlingguy.mysql

  tasks:
    - name: Open port for MySQL
      ufw:
        rule: allow
        port: "3306"
        proto: tcp
